FROM node:22-alpine AS dependencies

WORKDIR /app
    
COPY package*.json ./

RUN npm ci --omit=dev

FROM node:22-alpine AS runtime 

WORKDIR /app

ENV NODE_ENV=production

COPY --from=dependencies /app/node_modules ./node_modules
COPY package*.json ./
COPY src ./src

EXPOSE 9000

CMD ["node", "src/index.js"]